/**
 * Furniture kit registry — every asset here has a verified CC0 license recorded
 * in public/assets/MANIFEST.md. One coherent realistic style (Poly Haven).
 * Filled by the assets agent; presets (src/furnish/presets.ts) pick from here.
 */
import { KIT } from './kit.data'
import { PROCEDURAL } from './procedural.meta'

export type KitCategory =
  | 'bed'
  | 'bedside'
  | 'wardrobe'
  | 'sofa'
  | 'armchair'
  | 'coffee-table'
  | 'tv-unit'
  | 'dining-table'
  | 'dining-chair'
  | 'desk'
  | 'chair'
  | 'shelf'
  | 'lamp'
  | 'rug'
  | 'plant'
  | 'kitchen'
  | 'bath'
  | 'other'

export interface KitAsset {
  id: string
  label: string
  category: KitCategory
  /** public path, e.g. "/assets/models/sofa_02.glb" */
  url: string
  /** bounding box in meters: x = width (left-right when facing front), y = height, z = depth */
  sizeM: { x: number; y: number; z: number }
  /** which local axis the asset's "front" faces after load (glTF, Y-up) */
  frontAxis: '+z' | '-z' | '+x' | '-x'
  source: string
  author: string
  license: 'CC0'
  /** approx bytes of the .glb, for the loader's budgeting */
  bytes?: number
  /** where the engine hangs it: floor (default, grounded), ceiling (top touches the ceiling), wall (centre at 1.5 m) */
  mount?: 'floor' | 'ceiling' | 'wall'
  /** height of the asset's BOTTOM above the floor, m; overrides `mount` (a TV on its unit, a frame on the wall) */
  mountY?: number
}

/** id → asset. Populated by src/furnish/kit.data.ts (generated by the assets agent). */
export { KIT } from './kit.data'

// kit.data.ts is generated, so mounts live here and are merged in by kitAsset().
const MOUNT: Record<string, KitAsset['mount']> = {
  ceiling_fan: 'ceiling',
  modern_ceiling_lamp_01: 'ceiling',
  wall_clock: 'wall',
  hanging_picture_frame_01: 'wall',
}

// kit.data.ts guesses '+z' for every model; these two have their width (sizeM.x) along glTF z,
// measured from the accessor bounds. Both are symmetric front/back, so the sign is cosmetic.
const FRONT: Record<string, KitAsset['frontAxis']> = {
  wooden_display_shelves_01: '+x',
  modern_coffee_table_01: '+x',
}

// bottom heights: clock just below door-head height; the pillows sit on sofa_3seat's cushions (procedural.ts SOFA_SEAT)
const MOUNT_Y: Record<string, number> = {
  wall_clock: 1.8,
  throw_pillows_01: 0.44,
}

/** Poly Haven kit + procedural assets (src/furnish/procedural.meta.ts), with mount/front overrides applied. */
export function kitAsset(id: string): KitAsset | undefined {
  const a = KIT[id] ?? PROCEDURAL[id]
  if (!a || !(MOUNT[id] || FRONT[id] || MOUNT_Y[id] !== undefined)) return a
  return { ...a, mount: MOUNT[id] ?? a.mount, frontAxis: FRONT[id] ?? a.frontAxis, mountY: MOUNT_Y[id] ?? a.mountY }
}

/** Bottom and top of an asset above the floor (ceiling items: unknown ceiling → treated as floor-to-top). */
export function heightRange(a: KitAsset): [number, number] {
  const y0 = a.mountY ?? (a.mount === 'wall' ? 1.5 - a.sizeM.y / 2 : 0)
  return [y0, y0 + a.sizeM.y]
}
