/**
 * Furniture kit registry — every asset here has a verified CC0 license recorded
 * in public/assets/MANIFEST.md. One coherent realistic style (Poly Haven).
 * Filled by the assets agent; presets (src/furnish/presets.ts) pick from here.
 */
export type KitCategory =
  | 'bed'
  | 'bedside'
  | 'wardrobe'
  | 'sofa'
  | 'armchair'
  | 'coffee-table'
  | 'tv-unit'
  | 'dining-table'
  | 'dining-chair'
  | 'desk'
  | 'chair'
  | 'shelf'
  | 'lamp'
  | 'rug'
  | 'plant'
  | 'kitchen'
  | 'bath'
  | 'other'

export interface KitAsset {
  id: string
  label: string
  category: KitCategory
  /** public path, e.g. "/assets/models/sofa_02.glb" */
  url: string
  /** bounding box in meters: x = width (left-right when facing front), y = height, z = depth */
  sizeM: { x: number; y: number; z: number }
  /** which local axis the asset's "front" faces after load (glTF, Y-up) */
  frontAxis: '+z' | '-z' | '+x' | '-x'
  source: string
  author: string
  license: 'CC0'
  /** approx bytes of the .glb, for the loader's budgeting */
  bytes?: number
}

/** id → asset. Populated by src/furnish/kit.data.ts (generated by the assets agent). */
export { KIT } from './kit.data'
