/**
 * Furniture kit registry — every asset here has a verified CC0 license recorded
 * in public/assets/MANIFEST.md. One coherent realistic style (Poly Haven).
 * Filled by the assets agent; presets (src/furnish/presets.ts) pick from here.
 */
import { KIT } from './kit.data'
import { planterAsset, PROCEDURAL } from './procedural.meta'

export type KitCategory =
  | 'bed'
  | 'bedside'
  | 'wardrobe'
  | 'sofa'
  | 'armchair'
  | 'coffee-table'
  | 'tv-unit'
  | 'dining-table'
  | 'dining-chair'
  | 'desk'
  | 'chair'
  | 'shelf'
  | 'lamp'
  | 'rug'
  | 'plant'
  | 'kitchen'
  | 'bath'
  | 'other'

type Generic = 'kitchen' | 'lamp' | 'bath' | 'other'
/**
 * What a clickable thing IS, for buyers' notes today and a catalog slot later: a small fixed vocabulary.
 * Parts (door-handle, basin, mixer, window-glass…) are clickable pieces inside a door, window, vanity or shower.
 */
export type ObjectKind =
  | Exclude<KitCategory, Generic>
  | 'wall' | 'floor' | 'ceiling'
  | 'door' | 'door-leaf' | 'door-handle' | 'door-frame' | 'passage' | 'window' | 'window-frame' | 'window-glass' | 'curtain'
  | 'tv' | 'art' | 'clock' | 'cushions' | 'ottoman' | 'decor'
  | 'ceiling-light' | 'ceiling-fan' | 'ac' | 'stair'
  | 'kitchen-cabinet' | 'sink' | 'hob' | 'hood' | 'fridge'
  | 'toilet' | 'vanity' | 'basin' | 'mixer' | 'mirror' | 'shower' | 'shower-tray' | 'shower-glass' | 'shower-head'

export interface KitAsset {
  id: string
  label: string
  category: KitCategory
  /** public path, e.g. "/assets/models/sofa_02.glb" */
  url: string
  /** bounding box in meters: x = width (left-right when facing front), y = height, z = depth */
  sizeM: { x: number; y: number; z: number }
  /** which local axis the asset's "front" faces after load (glTF, Y-up) */
  frontAxis: '+z' | '-z' | '+x' | '-x'
  source: string
  author: string
  license: 'CC0'
  /** approx bytes of the .glb, for the loader's budgeting */
  bytes?: number
  /** where the engine hangs it: floor (default, grounded), ceiling (top touches the ceiling; overhead: no sun shadow, not a view target), wall (centre at 1.5 m) */
  mount?: 'floor' | 'ceiling' | 'wall'
  /** height of the asset's BOTTOM above the floor, m; overrides `mount` (a TV on its unit, a frame on the wall) */
  mountY?: number
  /** what it is (see ObjectKind); default from category */
  kind?: ObjectKind
}

/** id → asset. Populated by src/furnish/kit.data.ts (generated by the assets agent). */
export { KIT } from './kit.data'

// kit.data.ts is generated, so mounts live here and are merged in by kitAsset().
const MOUNT: Record<string, KitAsset['mount']> = {
  ceiling_fan: 'ceiling',
  modern_ceiling_lamp_01: 'ceiling',
  wall_clock: 'wall',
  hanging_picture_frame_01: 'wall',
}

// kit.data.ts guesses '+z' for every model; these two have their width (sizeM.x) along glTF z,
// measured from the accessor bounds. Both are symmetric front/back, so the sign is cosmetic.
const FRONT: Record<string, KitAsset['frontAxis']> = {
  wooden_display_shelves_01: '+x',
  modern_coffee_table_01: '+x',
}

const KIND: Record<string, ObjectKind> = {
  ceiling_fan: 'ceiling-fan',
  wall_clock: 'clock',
  hanging_picture_frame_01: 'art',
  throw_pillows_01: 'cushions',
  ottoman_01: 'ottoman',
  electric_stove: 'hob',
}

// bottom heights: clock centred at 2.4 m, above the 2.1 m door heads; the pillows sit on sofa_3seat's 0.45 m seat cushions
const MOUNT_Y: Record<string, number> = {
  wall_clock: 2.24,
  throw_pillows_01: 0.44,
}

/** Poly Haven kit + procedural assets (src/furnish/procedural.meta.ts), with mount/front overrides applied. */
export function kitAsset(id: string): KitAsset | undefined {
  const a = KIT[id] ?? PROCEDURAL[id] ?? planterAsset(id)
  if (!a || !(MOUNT[id] || FRONT[id] || MOUNT_Y[id] !== undefined || KIND[id])) return a
  return { ...a, mount: MOUNT[id] ?? a.mount, frontAxis: FRONT[id] ?? a.frontAxis, mountY: MOUNT_Y[id] ?? a.mountY, kind: KIND[id] ?? a.kind }
}

const GENERIC: Record<Generic, ObjectKind> = { kitchen: 'kitchen-cabinet', lamp: 'ceiling-light', bath: 'decor', other: 'decor' }
export const objectKind = (a: KitAsset): ObjectKind => a.kind ?? GENERIC[a.category as Generic] ?? (a.category as ObjectKind)

/** A ceiling fixture that carries the room's light: flush light, pendant or fan (its light kit). */
export function isCeilingLight(assetId: string): boolean {
  const a = kitAsset(assetId)
  return !!a && ['ceiling-light', 'ceiling-fan'].includes(objectKind(a))
}

/** Bottom and top of an asset above the floor (ceiling items: unknown ceiling → treated as floor-to-top). */
export function heightRange(a: KitAsset): [number, number] {
  const y0 = a.mountY ?? (a.mount === 'wall' ? 1.5 - a.sizeM.y / 2 : 0)
  return [y0, y0 + a.sizeM.y]
}

type Size3 = { x: number; y: number; z: number }

/** A placement's real size (m): its own `sizeM` override (a resized piece), else the kit size × scale. */
export function placementSize(p: { assetId: string; scale?: number; sizeM?: Size3 }): Size3 {
  if (p.sizeM) return p.sizeM
  const s = kitAsset(p.assetId)?.sizeM ?? { x: 1, y: 1, z: 1 }
  const k = p.scale ?? 1
  return { x: s.x * k, y: s.y * k, z: s.z * k }
}

/**
 * Size limits (m) for pieces that may be stretched: procedural builders that rebuild properly at any size within
 * them (a wider wardrobe gets another door, not stretched handles). null = move / turn only (every scanned glTF).
 * min = max on an axis: that axis is fixed (a table's height, a rug's pile, a larder's depth in the kitchen run).
 * The only shelf (wooden_display_shelves_01) is a scan: move / turn only.
 */
const lim = (min: [number, number, number], max: [number, number, number]) => ({ min: { x: min[0], y: min[1], z: min[2] }, max: { x: max[0], y: max[1], z: max[2] } })
// 0.9 m (two 0.45 m doors) to 3.0 m (five 0.6 m doors); up to 2.6 m tall under a 3.0 m ceiling
const WARDROBE = lim([0.9, 1.8, 0.5], [3.0, 2.6, 0.65])
const CLOSET = lim([0.6, 1.8, 0.5], [3.0, 2.6, 0.65])
const RUG = lim([1.2, 0.012, 0.8], [4.0, 0.012, 3.0])
// headboard width: a 0.9 m single mattress to a 2.0 m king (bed_* = mattress + 0.16)
const BED = lim([1.06, 1.15, 2.16], [2.16, 1.15, 2.16])
const RESIZE: Record<string, { min: Size3; max: Size3 }> = {
  wardrobe_tall: WARDROBE,
  wardrobe_2door: WARDROBE,
  closet_rail: CLOSET,
  closet_rail_s: CLOSET,
  kitchen_tall: lim([0.45, 1.8, 0.62], [1.2, 2.4, 0.62]),
  fridge: lim([0.55, 1.5, 0.6], [0.9, 2.0, 0.75]),
  desk_oak: lim([1.0, 0.75, 0.5], [2.0, 0.75, 0.9]),
  dining_table: lim([0.9, 0.75, 0.75], [2.6, 0.75, 1.2]), // 2 to 10 seats
  rug_rect_large: RUG,
  rug_rect_small: RUG,
  ...Object.fromEntries(Object.keys(PROCEDURAL).filter((id) => id.startsWith('bed_')).map((id) => [id, BED])),
}
export const resizeLimits = (assetId: string): { min: Size3; max: Size3 } | null => RESIZE[assetId] ?? null
